"""Tests for the rollout store Python bindings (local/embedded path).

The embedded `RolloutStore.open` path exercises the exact same binding surface
(JSON marshalling of records/DTOs, base64 blob handling, projection) that the
remote path uses, since both dispatch through the unified Rust `RolloutStore`
enum. Remote-specific wiring (HTTP) is covered by the Rust client tests.
"""

from __future__ import annotations

import tempfile

import pytest
from lance_context import RolloutStore


@pytest.fixture()
def store_uri():
    with tempfile.TemporaryDirectory() as d:
        yield d


def test_add_dict_list_get(store_uri):
    store = RolloutStore.open(store_uri)
    assert store.version() >= 0

    resp = store.add(
        {
            "id": "row-0",
            "rollout_id": "traj-1",
            "problem_id": "p-1",
            "role": "assistant",
            "content": "the answer is 42",
            "reward": 1.0,
            "policy_version": "ckpt-7",
        }
    )
    assert resp["count"] == 1
    assert resp["ids"] == ["row-0"]

    # `add` is durable on return but not visible until the memtable is sealed.
    store.flush()

    rows = store.list()
    assert len(rows) == 1
    assert rows[0]["id"] == "row-0"
    assert rows[0]["rollout_id"] == "traj-1"
    assert rows[0]["reward"] == 1.0
    assert rows[0]["policy_version"] == "ckpt-7"

    fetched = store.get("row-0")
    assert fetched is not None
    assert fetched["id"] == "row-0"
    assert store.get("missing") is None


def test_add_many_and_add_one(store_uri):
    store = RolloutStore.open(store_uri)
    store.add(
        [
            {"id": f"row-{i}", "rollout_id": "traj-1", "reward": float(i)}
            for i in range(3)
        ]
    )
    store.add_one(id="row-3", rollout_id="traj-1", reward=3.0)
    store.flush()

    rows = store.list()
    assert {r["id"] for r in rows} == {"row-0", "row-1", "row-2", "row-3"}


def test_id_autogenerated_when_omitted(store_uri):
    import uuid

    store = RolloutStore.open(store_uri)
    # No `id` field -> the binding mints a UUID4 for us.
    resp = store.add({"rollout_id": "traj-1", "reward": 1.0})
    assert resp["count"] == 1
    (generated,) = resp["ids"]
    # Round-trips as a valid UUID and is fetchable by the generated id.
    assert uuid.UUID(generated).version == 4
    store.flush()
    row = store.get(generated)
    assert row is not None and row["id"] == generated

    # add_one without id also works and yields distinct ids.
    r2 = store.add_one(rollout_id="traj-1")
    assert r2["ids"][0] != generated


def test_binary_payload_roundtrip(store_uri):
    store = RolloutStore.open(store_uri)
    blob = b"\x00\x01\x02trace-bytes"
    store.add(
        {
            "id": "art-0",
            "rollout_id": "traj-1",
            "role": "artifact",
            "content_type": "image/png",
            "artifact_type": "excel_grade_screenshot",
            "binary_payload": blob,
            "payload_size": len(blob),
        }
    )
    store.flush()

    # list/get project the blob column out (cheap metadata scans).
    row = store.get("art-0")
    assert row is not None
    assert row.get("binary_payload") is None
    assert row["payload_size"] == len(blob)
    # artifact_type is a first-class column, orthogonal to content_type.
    assert row["content_type"] == "image/png"
    assert row["artifact_type"] == "excel_grade_screenshot"

    # get_blob materializes the bytes on demand.
    assert store.get_blob("art-0") == blob
    assert store.get_blob("missing") is None


def test_empty_add_rejected(store_uri):
    store = RolloutStore.open(store_uri)
    with pytest.raises(ValueError):
        store.add([])


def test_reopen_sees_prior_rows(store_uri):
    store = RolloutStore.open(store_uri)
    store.add({"id": "row-0", "rollout_id": "traj-1"})
    # Seal before dropping: an unsealed memtable is durable in the WAL but is
    # not replayed into a readable generation by a fresh reader.
    store.flush()
    del store

    reopened = RolloutStore.open(store_uri)
    rows = reopened.list()
    assert len(rows) == 1
    assert rows[0]["id"] == "row-0"


def test_list_filters_before_pagination(store_uri):
    store = RolloutStore.open(store_uri)
    store.add(
        [
            {
                "id": "row-a",
                "rollout_id": "traj-a",
                "problem_id": "problem-a",
                "policy_version": "ckpt-1",
                "role": "assistant",
                "include_in_training": True,
            },
            {
                "id": "row-b",
                "rollout_id": "traj-b",
                "problem_id": "problem-b",
                "policy_version": "ckpt-2",
                "role": "assistant",
                "include_in_training": False,
            },
            {
                "id": "row-c",
                "rollout_id": "traj-b",
                "problem_id": "problem-b",
                "policy_version": "ckpt-2",
                "role": "artifact",
                "artifact_type": "screenshot",
                "include_in_training": False,
            },
        ]
    )
    store.flush()

    rows = store.list(
        filters={"policy_version": "ckpt-2", "include_in_training": False}
    )
    assert {row["id"] for row in rows} == {"row-b", "row-c"}

    page = store.list(
        limit=1,
        offset=1,
        filters={"policy_version": "ckpt-2", "include_in_training": False},
    )
    assert len(page) == 1
    assert page[0]["policy_version"] == "ckpt-2"


def test_list_rejects_invalid_filter_fields(store_uri):
    store = RolloutStore.open(store_uri)
    with pytest.raises(RuntimeError, match="unsupported rollout filter"):
        store.list(filters={"reward": 1.0})


def test_get_trajectory_orders_rows(store_uri):
    store = RolloutStore.open(store_uri)
    store.add(
        [
            {"id": "row-a", "rollout_id": "target", "sequence_order": 2},
            {"id": "other", "rollout_id": "other", "sequence_order": 0},
            {"id": "row-b", "rollout_id": "target", "sequence_order": 0},
        ]
    )
    store.flush()

    rows = store.get_trajectory("target")
    assert [row["id"] for row in rows] == ["row-b", "row-a"]
